name: Irena Mandel
favicon: null
layout_spectrum: 0.50367
typography_spectrum: 1
title: Irena Mandel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6c5c3d'
    - '#897751'
    - '#acac93'
    - '#3f3c06'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
